In [30]:
import pandas as pd

defra = pd.read_excel("guides_and_dbs/DEFRA_conversion-factors-2021-flat-file-automatic-processing.xlsm", 
                      sheet_name="Factors by Category", header=4)

# Step 1: Load using header from row 1 (row index = 1)
agribalyse_df = pd.read_excel("guides_and_dbs/AGRIBALYSE3.0.1_vf.xlsm", sheet_name="Synthese", header=1)

bio = pd.read_excel("guides_and_dbs/BioGrace_standard_values_-_version_4_-_Public.xlsm", 
                    sheet_name="Standard values", header=9)

/opt/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

ValueError: Worksheet named 'Factors by Category' not found

In [2]:
# bio = pd.read_excel("guides_and_dbs/BioGrace_standard_values_-_version_4_-_Public.xlsm", 
#                     sheet_name="Standard values", 
#                     header=None,  # don't treat any row as column names yet
#                     skiprows=5)   # skip top rows to reach actual data

# bio

In [4]:
agribalyse_df = agribalyse_df.loc[:,"LCI Name":"Changement climatique (kg CO2 eq/kg de produit)"]

In [5]:
agribalyse_df[agribalyse_df["LCI Name"].astype(str).str.contains("cocoa", case=False, na=False)]

,LCI Name,Saisonnalité,Transport par avion\n(1 : par avion),Livraison,Matériau d'emballage,Préparation,DQR - Note de qualité de la donnée (1 excellente ; 5 très faible),Score unique EF (mPt/kg de produit),Changement climatique (kg CO2 eq/kg de produit)
130,Cocoa butter,mix de consommation FR,0,Ambiant (long),Bouteille PET,Pas de préparation,2.53,1.669921,26.580789
271,"Instant cocoa or chocolate beverage, with suga...",mix de consommation FR,0,Ambiant (moyenne),Bouteille PETE,Pas de préparation,3.07,0.140724,1.544385
272,"Instant cocoa or chocolate beverage, with suga...",mix de consommation FR,0,Ambiant (moyenne),Bouteille PETE,Pas de préparation,3.07,0.140724,1.544385
361,"Cocoa powder, without sugar, powder, instant",mix de consommation FR,0,Ambiant (moyenne),Carton,Pas de préparation,2.77,1.658175,26.447131
506,"Dark chocolate bar, more than 40% cocoa, for c...",mix de consommation FR,0,Ambiant (moyenne),Carton,Pas de préparation,2.99,1.293344,18.584100
507,"Dark chocolate bar, more than 70% cocoa",mix de consommation FR,0,Ambiant (moyenne),Carton,Pas de préparation,2.99,1.293344,18.584100
508,"Dark chocolate bar, less than 70% cocoa",mix de consommation FR,0,Ambiant (moyenne),Carton,Pas de préparation,2.99,1.293344,18.584100
1895,"Cocoa or chocolate powder, for beverages, with...",mix de consommation FR,0,Ambiant (moyenne),Verre,Pas de préparation,2.77,1.698002,26.885838
1896,"Cocoa or chocolate powder, for beverages, with...",mix de consommation FR,0,Ambiant (moyenne),Verre,Pas de préparation,2.77,1.698002,26.885838
1897,"Cocoa or chocolate powder, for beverages, with...",mix de consommation FR,0,Ambiant (moyenne),Verre,Pas de préparation,2.77,1.698002,26.885838
2035,"Shortbread cookie with cocoa or chocolate, or ...",mix de consommation FR,0,Ambiant (long),Carton,Pas de préparation,2.03,0.616117,7.550818

In [35]:
defra[defra["Lookup"].astype(str).str.contains("warehouse", case=False, na=False)]

Empty DataFrame
Columns: [Scope, Level 1, Level 2, Level 3, Level 4, Column Text, UOM (simple), UOM, GHG, Lookup, GHG Conversion Factor 2021]
Index: []

In [8]:
electricity_scope2 = defra[
    (defra["Scope"] == "Scope 2") &
    (
        defra["Level 1"].astype(str).str.contains("electricity", case=False, na=False) |
        defra["Level 2"].astype(str).str.contains("electricity", case=False, na=False) |
        defra["Level 3"].astype(str).str.contains("electricity", case=False, na=False)
    )
]

In [9]:
electricity_scope2[electricity_scope2["GHG"] == "kg CO2e"]

,Scope,Level 1,Level 2,Level 3,Level 4,Column Text,UOM (simple),UOM,GHG,Lookup,GHG Conversion Factor 2021
1968,Scope 2,UK electricity,Electricity generated,Electricity: UK,NaN,NaN,kWh,kWh,kg CO2e,Electricity: UK,0.21233
1972,Scope 2,UK electricity for Evs,Cars (by market segment),Mini,NaN,Plug-in Hybrid Electric Vehicle,km,km,kg CO2e,Mini km,NaN
1976,Scope 2,UK electricity for Evs,Cars (by market segment),Mini,NaN,Plug-in Hybrid Electric Vehicle,miles,miles,kg CO2e,Mini miles,NaN
1980,Scope 2,UK electricity for Evs,Cars (by market segment),Mini,NaN,Battery Electric Vehicle,km,km,kg CO2e,Mini km,0.04035
1984,Scope 2,UK electricity for Evs,Cars (by market segment),Mini,NaN,Battery Electric Vehicle,miles,miles,kg CO2e,Mini miles,0.06493
...,...,...,...,...,...,...,...,...,...,...,...
2256,Scope 2,UK electricity for Evs,Vans,Average (up to 3.5 tonnes),NaN,Plug-in Hybrid Electric Vehicle,miles,miles,kg CO2e,Average (up to 3.5 tonnes) miles,NaN
2260,Scope 2,UK electricity for Evs,Vans,Average (up to 3.5 tonnes),NaN,Plug-in Hybrid Electric Vehicle,tonne.km,tonne.km,kg CO2e,Average (up to 3.5 tonnes) tonne.km,NaN
2264,Scope 2,UK electricity for Evs,Vans,Average (up to 3.5 tonnes),NaN,Battery Electric Vehicle,km,km,kg CO2e,Average (up to 3.5 tonnes) km,0.0502
2268,Scope 2,UK electricity for Evs,Vans,Average (up to 3.5 tonnes),NaN,Battery Electric Vehicle,miles,miles,kg CO2e,Average (up to 3.5 tonnes) miles,0.08078
2272,Scope 2,UK electricity for Evs,Vans,Average (up to 3.5 tonnes),NaN,Battery Electric Vehicle,tonne.km,tonne.km,kg CO2e,Average (up to 3.5 tonnes) tonne.km,0.22551

In [10]:
elect_scope2 = defra[
    (defra["Scope"] == "Scope 2") &
    (defra["Level 1"].astype(str).str.contains("UK electricity", case=False, na=False)) &
    (defra["Level 2"].astype(str).str.contains("Electricity generated", case=False, na=False)) &
    (defra["UOM"] == "kWh") &
    (defra["GHG"] == "kg CO2e")
]

In [11]:
elect_scope2

,Scope,Level 1,Level 2,Level 3,Level 4,Column Text,UOM (simple),UOM,GHG,Lookup,GHG Conversion Factor 2021
1968,Scope 2,UK electricity,Electricity generated,Electricity: UK,NaN,NaN,kWh,kWh,kg CO2e,Electricity: UK,0.21233

In [36]:
defra[defra["Level 1"].astype(str).str.contains("storage|warehouse", case=False, na=False)]

Empty DataFrame
Columns: [Scope, Level 1, Level 2, Level 3, Level 4, Column Text, UOM (simple), UOM, GHG, Lookup, GHG Conversion Factor 2021]
Index: []